language: rust

sudo: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

before_script:
  - export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
  - which mdbook || cargo install mdbook
  - pip install 'travis-cargo<0.2' --user

os:
  - linux

script:
  - cargo test --all --all-features
  - cargo doc --all --no-deps --all-features

after_success:
  - mdbook build
  - cp ./index.html ./rust.css ./target/doc/
  - ./doc_upload.py

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: A/zuPuIu03Z+rqnDS/NNNjbXrg8Nc9lEGKzcBdpHgnyd23z37zreEEAKzFhjJKMx0np0ntDo5LVeLgT6d7fGaDFsJrBZHej3pxuG81MAJdLEmJNaCLCc1eCbwDHgJkEJ5HsblHTrYK0RjBvNL5I8+URuzEqXkwVr7UHJv5px1ZA=

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxldmFucyUzQXNhZmFyYWRlZy5uZXQvJTIxRkt4aGprSUNwakJWelZlQ2RGJTNBc2FmYXJhZGVnLm5ldA"
        on_success: change
        on_failure: always
        on_start: never
